SET session_replication_role = replica;

--
-- PostgreSQL database dump
--

-- \restrict 8Zqmb4jrv1POfM7JqdNoPpX3FpX3Z6hCKzRo9zqZuAYwmY8ItFFUrlt2JdqZjUg

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: trees; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO "public"."trees" ("id", "foto", "nome_cientifico", "nome_popular", "origem", "decidua_perenifolia", "epoca_floracao", "epoca_frutificacao", "altura_adulta_max_m", "porte_altura_classe", "diametro_copa_adulto_max_m", "copa_classe", "dap_adulto_max_cm", "altura_primeira_bifurcacao_m", "forma_copa", "faixa_serv_min_m_recomendada", "berco_area_min_m2_recomendada", "volume_solo_min_m3_recomendado", "compat_fiacao", "potencial_dano_calcada_1a5", "tolerancia_sol_pleno", "tolerancia_meia_sombra", "tolerancia_sombra", "tolerancia_seca_1a5", "tolerancia_encharcamento_1a5", "tolerancia_poluicao_atmosferica_1a5", "tolerancia_compactacao_solo_1a5", "tolerancia_ventos_fortes_1a5", "potencial_sujeira_1a5", "presenca_espinhos", "presenca_subst_irritantes", "atracao_fauna_1a5", "tolerancia_poda_1a5", "potencial_sombra_1a5", "contribuicao_biodiversidade_1a5", "ativa") VALUES
	(6, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774376103614-ju119qt4cvl.jpg', 'Albizia niopoides (Spruce ex Benth.) Burkart', 'Farinha-seca', 'Nativa BR', 'Semidecídua', 'Set-Jan', 'Jul-Dez', 35, 'Grande', 20, 'Grande', 80, '4-6', 'Arredondada / Espalhada', 1, 1, 0.6, 'N', 2, true, false, false, 4, 2, 3, 2, 3, 3, false, false, 4, 4, 5, 4, false),
	(29, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/plinia-cauliflora-mart-kausel.jpg', 'Plinia cauliflora (Mart.) Kausel', 'Jabuticaba; Jabuticabeira', 'Nativa BR', 'Semidecídua', 'Jun-Ago; Nov-Dez', 'Ago-Set; Jan-Fev', 15.0, 'Médio', 6.0, 'Média', 40.0, '5,0-6,0', 'Arredondada', 1.2, 2.0, 1.2, 'A', 1, true, true, false, 2, 3, 3, 2, 3, 4, false, false, 5, 4, 4, 4, false),
	(30, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/spondias-dulcis.jpg', 'Spondias dulcis', 'Cajá-manga; cajarana; taperebá-do-sertão', 'Exótica', 'Decídua', 'Jul-Set', 'Set-Jan', 20.0, 'Grande', 8.0, 'Grande', 73.0, '4,0-4,5', 'Arredondada', 0.8, 3.0, 1.8, 'N', 3, true, true, false, 3, 2, 3, 2, 2, 4, false, false, 4, 4, 5, 3, false),
	(41, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/syagrus-romanzoffiana.jpg', 'Syagrus romanzoffiana', 'Jerivá', 'Nativa BR', 'Perenifólia', 'Nov-Mar', 'Mar-Nov', 15.0, 'Médio', 8.0, 'Média', 40.0, '0', 'Colunar', 1.5, 2.25, 3.0, 'A', 1, true, true, false, 3, 2, 3, 2, 4, 4, false, false, 5, 2, 2, 5, true),
	(32, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/handroanthus-albus.jpg', 'Handroanthus albus', 'Ipê-branco', 'Nativa BR', 'Decídua', 'Jun-Set', 'Out-Dez', 30, 'Grande', 20, 'Grande', 100, NULL, 'Arredondada', 3, 8, 4, 'N', 3, true, true, false, 4, 2, 4, 3, 3, 4, false, false, 4, 4, 5, 4, false),
	(2, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Extremosa_%28Lagerstroemia_indica%29_em_um_fim_de_tarde_em_Bagé-RS_-_55013179934.jpg/960px-Extremosa_%28Lagerstroemia_indica%29_em_um_fim_de_tarde_em_Bagé-RS_-_55013179934.jpg', 'Lagerstroemia indica', 'Resedá extremosa', 'Exótica', 'Decídua', 'Verão', NULL, 8.0, 'Médio', 5.0, 'Pequena', 30.0, '1,8 - 2,5', 'Arredondada/Globosa', 0.8, 1.0, 1.5, 'A', 1, true, true, false, 5, 3, 4, 4, 3, 1, false, false, 3, 5, 3, 3, true),
	(4, 'https://centraldasplantas.com.br/wp-content/uploads/2020/07/Escumilha-africana-2.jpg', 'Sapindus saponaria', 'Sabão-de-soldado', 'Nativa BR', 'Perenifólia', 'Abr-Jul', 'Set-Out', 9, 'Médio', 8, 'Média', 40, '2,0 - 3,0', 'Arredondada/Globosa', 1.2, 1.5, 3, 'C', 2, true, true, false, 5, 3, 4, 4, 4, 2, false, false, 4, 4, 4, 4, true),
	(5, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/eugenia-pyriformis-cambess.png', 'Eugenia pyriformis Cambess.', 'Uvaia', 'Nativa BR', 'Semidecídua', 'Ago-Set', 'Set-Jan', 13, 'Médio', 7, 'Média', 50, '1,8-2,2', 'Arredondada', 0.7, 1, 0.6, 'C', 2, true, true, true, 3, 4, 3, 2, 3, 4, false, false, 5, 4, 4, 4, true),
	(11, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774376755617-oa2v5te4g.jpg', 'Platypodium elegans Vogel', 'Amendoim-do-campo', 'Nativa BR', 'Semidecídua', 'Set-Nov', 'Set-Out', 12, 'Médio', 15, 'Média', 50, '10-15', 'Espalhada', 3, 6, 12, 'N', 4, true, true, false, 4, 2, 3, 2, 3, 3, false, false, NULL, 3, NULL, NULL, true),
	(13, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774376857336-srr0tw4zidj.jpg', 'Holocalyx balansae Micheli', 'Alecrim-de-campinas', 'Nativa BR', 'Semidecídua', 'Out-Nov', 'Dez-Fev', 25, 'Grande', 12, 'Grande', 80, '2,5-4,0', 'Globosa', 3, 6, 12, 'N', 4, true, true, true, 2, 1, 3, 3, 3, 3, false, true, 4, 3, 5, 4, true),
	(19, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774377192125-52x28aeawux.webp', 'Calyptranthes clusiifolia (Miq.) O.Berg', 'Araçarana', 'Nativa BR', 'Perenifólia', NULL, NULL, 15, 'Médio', NULL, 'Média', NULL, NULL, 'Arredondada', 2, 25, 1, 'A', 2, true, true, false, 3, 2, 3, 3, 3, 2, false, false, 4, 4, 4, 4, true),
	(12, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774376814778-yjubqu3xnbf.jpg', 'Ligustrum lucidum W.T. Aiton', 'Alfeneiro-do-japão', 'Exótica', 'Perenifólia', 'Out-Jan', 'Jan-Abr', 15, 'Médio', 10, 'Média', 50, '2,0-3,0', 'Globosa', 2, 3, 6, 'A', 3, true, true, true, 4, 2, 3, 3, 3, 4, false, false, 4, 4, 4, 2, true),
	(26, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/malpighia-glabra-l.jpg', 'Malpighia glabra L.', 'Acerola; Aceroleira; Cereja-das-antilhas; Cerejeira-do-Pará', 'Exótica', 'Perenifólia', 'Jan-Dez', 'Jan-Dez', 6.0, 'Pequeno', 4.0, 'Média', 20.0, '2,0 - 2,5', 'Arredondada', 0.6, 1.0, 0.6, 'C', 2, true, true, false, 4, 1, 3, 2, 3, 4, false, false, 4, 4, 3, 3, false),
	(21, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774377278711-xps45t4hvh.jpg', 'Dombeya wallichii', 'Astrapéia', 'Exótica', 'Semidecídua', 'Abr-Jul', NULL, 12, 'Médio', NULL, 'Média', NULL, NULL, 'Arredondada', 2, 4, 8, 'C', 2, true, true, false, 3, 2, 3, 2, 3, 3, false, false, 5, 4, 3, 4, true),
	(23, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/handroanthus-impetiginosus-mart-ex-dc-mattos.jpg', 'Handroanthus impetiginosus (Mart. ex DC.) Mattos', 'Ipê-roxo-de-bola', 'Nativa BR', 'Decídua', 'Mai-Ago', 'Set-Out', 18.0, 'Grande', 8.0, 'Grande', 80.0, '2,5-3,5', 'Globosa', 2.5, 6.0, 12.0, 'N', 2, true, true, false, 4, 2, 3, 3, 3, 4, false, false, 4, 3, 4, 4, true),
	(27, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/annona-squamosa-l.jpg', 'Annona squamosa L.', 'Pinha', 'Exótica', 'Decídua', 'Set-Nov', 'Jan-Mai', 7.0, 'Pequeno', 6.0, 'Média', 20.0, '0,5-1,0', 'Arredondada / Espalhada', 1.5, 2.25, 3.0, 'C', 3, true, true, false, 4, 1, 4, 2, 2, 3, false, false, 4, 4, 3, 3, false),
	(28, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/persea-americana.avif', 'Persea americana', 'Abacateiro; Abacate', 'Exótica', 'Perenifólia', 'Ago-Set', 'Mar-Jul', 20.0, 'Grande', 10.0, 'Grande', 50.0, '1,5-2,5', 'Arredondada a Irregular', 3.0, 12.0, 30.0, 'N', 4, true, true, false, 3, 1, 3, 2, 3, 5, false, false, 4, 4, 5, 3, false),
	(25, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/eugenia-uniflora.webp', 'Eugenia uniflora', 'Pitangueira', 'Nativa BR', 'Semidecídua', 'Ago-Dez', 'Out-Jan', 12.0, 'Médio', 6.0, 'Média', 50.0, '1,8-2,5', 'Arredondada', 2.0, 1.2, 20.0, 'C', 2, true, true, false, 4, 3, 3, 3, 3, 4, false, false, 5, 5, 4, 4, true),
	(74, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/vitex-polygama.jpg', 'Vitex polygama', 'Tarumã-do-cerrado', 'Nativa BR', 'Perenifólia', 'Out-Nov', 'Dez-Jan', 10, 'Médio', 5, 'Média', 40, '1,5 - 2,5', 'Globosa', 2, 1, 4, 'A', 2, true, true, false, 3, 3, 3, 3, 3, 3, false, false, 4, 3, 4, 4, true),
	(168, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/guapira-opposita.jpg', 'Guapira opposita', 'Maria-mole', 'Nativa BR', 'Perenifólia', 'Out-Dez', 'Dez-Fev', 15.0, 'Médio', 5.0, 'Média', 50.0, '1,5 - 2,5', 'Arredondada', 2.5, 2.0, 10.0, 'A', 2, true, true, true, 3, 4, 3, 3, 4, 2, false, false, 4, 3, 4, 4, true),
	(169, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/guarea-guidonia.jpg', 'Guarea guidonia', 'Marinheiro, camboatã', 'Nativa BR', 'Perenifólia', 'Ago-Out', 'Dez-Fev', 20.0, 'Grande', 8.0, 'Grande', 60.0, '3,0 - 5,0', 'Arredondada', 3.0, 3.0, 20.0, 'N', 3, true, true, false, 2, 5, 3, 3, 3, 3, false, false, 5, 3, 5, 5, true),
	(172, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/erythrina-falcata.jpg', 'Erythrina falcata', 'Mulungu', 'Nativa BR', 'Decídua', 'Jun-Set', 'Out-Dez', 20.0, 'Grande', 10.0, 'Grande', 80.0, '2,0 - 4,0', 'Espalhada', 3.0, 3.0, 20.0, 'N', 4, true, false, false, 2, 5, 3, 3, 3, 3, true, false, 5, 2, 5, 5, true),
	(31, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/bougainvillea-glabra-choisy.webp', 'Bougainvillea glabra Choisy', 'Primavera', 'Nativa BR', 'Semidecídua', 'Set-Mar', 'Mar-Mai', 10.0, 'Médio', 6.0, 'Média', 30.0, '1,5-2,5', 'Irregular / Espalhada', 2.5, 4.0, 8.0, 'A', 2, true, true, false, 4, 1, 3, 3, 4, 4, true, false, 4, 5, 3, 3, false),
	(174, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/physocalymma-scaberrimum.jpg', 'Physocalymma scaberrimum', 'Nó-de-porco, resedá nacional', 'Nativa BR', 'Decídua', 'Set-Nov', 'Dez-Fev', 20.0, 'Grande', 8.0, 'Grande', 60.0, '3,0 - 5,0', 'Arredondada', 3.0, 3.0, 20.0, 'N', 3, true, false, false, 4, 2, 3, 3, 3, 3, false, false, 4, 2, 5, 4, true),
	(177, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/bauhinia-variegata.webp', 'Bauhinia variegata', 'Pata-de-vaca', 'Exótica', 'Semidecídua', 'Ago-Out', 'Out-Dez', 10.0, 'Médio', 6.0, 'Média', 40.0, '1,5 - 2,5', 'Arredondada', 2.5, 2.0, 10.0, 'A', 2, true, true, false, 3, 2, 4, 3, 3, 3, false, false, 4, 3, 4, 3, true),
	(178, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/bauhinia-blakeana.jpg', 'Bauhinia blakeana', 'Pata-de-vaca', 'Exótica', 'Perenifólia', 'Mai-Out', 'Não produz', 8.0, 'Médio', 5.0, 'Média', 30.0, '1,0 - 1,5', 'Arredondada', 2.0, 1.5, 8.0, 'A', 2, true, true, false, 3, 2, 4, 3, 3, 2, false, false, 3, 3, 4, 2, true),
	(179, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/bauhinia-monandra.jpg', 'Bauhinia monandra', 'Pata-de-vaca rosa', 'Exótica', 'Semidecídua', 'Out-Dez', 'Dez-Fev', 12.0, 'Médio', 6.0, 'Média', 40.0, '1,5 - 2,5', 'Arredondada', 2.5, 2.0, 10.0, 'A', 2, true, true, false, 3, 2, 4, 3, 3, 3, false, false, 4, 3, 4, 3, true),
	(180, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/bauhinia-purpurea.webp', 'Bauhinia purpurea', 'Pata-de-vaca roxa', 'Exótica', 'Semidecídua', 'Set-Nov', 'Dez-Mar', 10.0, 'Médio', 6.0, 'Média', 40.0, '1,5 - 2,5', 'Arredondada', 2.5, 2.0, 10.0, 'A', 2, true, true, false, 3, 2, 4, 3, 3, 3, false, false, 4, 3, 4, 3, true),
	(181, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/senna-multijuga.jpg', 'Senna multijuga', 'Pau cigarra', 'Nativa BR', 'Semidecídua', 'Dez-Mar', 'Mar-Jun', 15.0, 'Médio', 6.0, 'Média', 40.0, '2,0 - 3,0', 'Arredondada', 2.5, 2.0, 10.0, 'A', 2, true, true, false, 3, 3, 4, 3, 3, 3, false, false, 5, 3, 4, 4, true),
	(182, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/gallesia-integrifolia.webp', 'Gallesia integrifolia', 'Pau d''alho', 'Nativa BR', 'Semidecídua', 'Dez-Fev', 'Fev-Mai', 30.0, 'Grande', 15.0, 'Grande', 120.0, '5,0 - 8,0', 'Arredondada', 4.0, 4.0, 30.0, 'N', 5, true, false, false, 3, 2, 3, 3, 4, 4, false, false, 5, 2, 5, 5, true),
	(183, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/calycophyllum-spruceanum.jpg', 'Calycophyllum spruceanum', 'Pau mulato', 'Nativa BR', 'Perenifólia', 'Jun-Ago', 'Set-Nov', 25.0, 'Grande', 10.0, 'Grande', 60.0, '4,0 - 6,0', 'Arredondada', 3.0, 3.0, 20.0, 'N', 2, true, true, false, 2, 4, 3, 3, 3, 2, false, false, 4, 2, 5, 5, true),
	(22, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774377309860-544lwmvqqke.jpg', 'Machaerium aculeatum', 'Bico-de-pato', 'Nativa BR', 'Decídua', 'Nov-Fev', 'Abr-Jul', 12.0, 'Médio', 7.0, 'Média', 40.0, 'Não encontrado', 'Arredondada', 2.5, 6.25, 1.0, 'A', 3, true, true, false, 3, 2, 3, 3, 3, 3, true, false, 3, 3, 3, 4, true),
	(34, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/duranta-erecta-l.jpg', 'Duranta erecta L.', 'pingo-de-ouro; violeteira', 'Exótica', 'Perenifólia', 'Jan-Dez', 'Jan-Dez', 6.0, 'Pequeno', 4.0, 'Pequena', 10.0, '0,3 - 0,8', 'Irregular', 1.0, 1.0, 1.0, 'C', 1, true, true, false, 3, 1, 3, 2, 2, 4, false, true, 3, 5, 2, 2, false),
	(36, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/malpighia-emarginata.webp', 'Malpighia emarginata', 'Acerola', 'Exótica', 'Perenifólia', 'Ano todo', 'Ano todo', 5.0, 'Pequeno', 4.0, 'Média', 20.0, NULL, 'Arredondada', 1.5, 2.0, 4.0, 'C', 1, true, true, false, 3, 2, 3, 3, 3, 3, false, false, 5, 4, 3, 4, false),
	(38, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/psidium-guajava.webp', 'Psidium guajava', 'Goiaba', 'Nativa BR', 'Perenifólia', 'Out-Nov', 'Jan-Fev', 10.0, 'Médio', 8.0, 'Média', 50.0, '2-3', 'Arredondada', 2.0, 4.0, 2.0, 'C', 3, true, true, false, 3, 4, 3, 3, 3, 4, false, false, 5, 4, 4, 4, false),
	(39, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/rhapis-excelsa.jpg', 'Rhapis excelsa', 'Palmeira-bambu', 'Exótica', 'Perenifólia', NULL, NULL, 3.0, 'Pequeno', 2.0, 'Pequena', 2.0, NULL, 'Irregular', 1.5, 2.25, 0.7, 'C', 1, false, true, true, 3, 3, 4, 3, 3, 2, false, false, 2, 4, 3, 3, false),
	(112, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/callistemon-viminalis.jpg', 'Callistemon viminalis', 'Calistemon', 'Exótica', 'Perenifólia', 'Jun-Set', 'Ano todo', 6.0, 'Pequeno', 5.0, 'Pequena', 25.0, '1.5-2.5', 'Pendente', 1.0, 1.0, 0.3, 'C', 1, true, true, false, 4, 2, 4, 4, 3, 3, false, false, 4, 5, 2, 3, true),
	(114, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/campomanesia-phaea.jpg', 'Campomanesia phaea', 'Cambuci', 'Nativa BR', 'Perenifólia', 'Ago-Nov', 'Jan-Fev', 5.0, 'Pequeno', 5.0, 'Pequena', 30.0, '1.5-2.5', 'Arredondada', 1.0, 1.0, 0.5, 'C', 2, true, true, false, 3, 3, 3, 3, 3, 3, false, false, 4, 4, 3, 4, true),
	(40, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/roystonea-oleracea.jpg', 'Roystonea oleracea', 'Palmeira-real', 'Exótica', 'Perenifólia', 'Jan-Abr', 'Jul-Dez', 25.0, 'Grande', 10.0, 'Grande', 70.0, 'Não aplicável', 'Globosa', 4.0, 10.0, 5.0, 'N', 4, true, true, false, 2, 3, 4, 3, 3, 4, false, false, 4, 3, 5, 3, false),
	(121, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/cassia-javanica.jpg', 'Cassia javanica', 'Cassia javanesa, cassia rosa', 'Exótica', 'Decídua', 'Out-Jan', 'Nov-Fev', 20.0, 'Grande', 12.0, 'Grande', 60.0, NULL, 'Pendente', 3.0, 4.0, 2.0, 'N', 4, true, true, false, 3, 2, 4, 3, 3, 4, false, false, 4, 4, 5, 3, true),
	(44, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/thuja-occidentalis.webp', 'Thuja occidentalis', 'Tuia', 'Exótica', 'Perenifólia', 'Abr-Jun', 'Set-Dez', 15.0, 'Médio', 6.0, 'Média', 100.0, NULL, 'Colunar', 3.0, 6.0, 12.0, 'N', 3, true, true, false, 2, 3, 4, 3, 4, 2, false, true, 3, 5, 4, 2, false),
	(124, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/cedrela-fissilis.jpg', 'Cedrela fissilis', 'Cedro', 'Nativa BR', 'Decídua', 'Ago-Set', 'Jun-Ago', 40.0, 'Grande', 15.0, 'Grande', 300.0, '15', 'Arredondada', 2.0, 4.0, 2.0, 'N', 4, true, true, false, 3, 3, 4, 3, 3, 4, false, false, 4, 4, 5, 5, true),
	(100, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/annona-squamosa.jpg', 'Annona squamosa', 'Fruta-do-conde', 'Exótica', 'Decídua', 'Set-Nov', 'Dez-Mar', 8.0, 'Médio', 6.0, 'Média', 30.0, '1.5-2.5', 'Arredondada', 1.5, 2.0, 4.0, 'C', 2, true, true, false, 4, 2, 3, 3, 3, 4, false, false, 4, 3, 3, 4, false),
	(126, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/sterculia-chicha-st-hil.jpg', 'Sterculia chicha St. Hil.', 'Chichá', 'Nativa BR', 'Semidecídua', 'Nov-Mar', 'Mai-Set', 20.0, 'Grande', NULL, 'Grande', NULL, NULL, 'Arredondada', 3.0, 6.0, 6.0, 'N', 4, true, true, false, 3, 3, 3, 3, 3, 3, false, false, 4, 3, 4, 4, true),
	(103, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/rhapis-excelsa-thunb-a-j-henry.jpg', 'Rhapis excelsa (Thunb.) A.J.Henry', 'Palmeira-bambu', 'Exótica', 'Perenifólia', 'Ver-ago', 'Set-Dez', 4.0, 'Pequeno', 3.0, 'Pequena', 15.0, 'Não aplica', 'Densa', 1.5, 1.5, 0.8, 'C', 1, true, true, true, 3, 3, 4, 3, 3, 2, false, false, 2, 5, 2, 2, false),
	(128, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/poecilanthe-parviflora.jpg', 'Poecilanthe parviflora', 'Coração-de-negro', 'Nativa BR', 'Perenifólia', 'Out-Jan', 'Jun-Set', 25.0, 'Grande', 15.0, 'Grande', 90.0, '10', 'Espalhada', 3.0, 8.0, 20.0, 'N', 3, true, true, false, 3, 3, 3, 3, 3, 3, false, false, 3, 3, 4, 4, true),
	(43, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tecoma-stans.webp', 'Tecoma stans', 'Ipê-amarelo-de-jardim', 'Exótica', 'Semidecídua', 'Ano todo', 'Ano todo', 6, 'Pequeno', 3, 'Pequena', 20, '0,5 - 1,0', 'Arredondada', 1.5, 0.8, 2, 'C', 2, true, true, false, 5, 2, 4, 4, 3, 2, false, false, 4, 5, 2, 2, false),
	(109, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/morus-nigra.jpeg', 'Morus nigra', 'Amoreira', 'Exótica', 'Decídua', 'Jul-Ago', 'Vermelho a preto carnoso', 12.0, 'Médio', 7.0, 'Média', NULL, 'Não encontrado', 'Pendente', 2.5, 4.0, 1.0, 'C', 3, true, true, false, 3, 2, 4, 3, 3, 4, false, false, 4, 4, 4, 3, true),
	(135, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/pterodon-emarginatus.jpg', 'Pterodon emarginatus', 'Faveira, sucupira lisa', 'Nativa BR', 'Decídua', 'Set-Nov', 'Jun-Ago', 16.0, 'Grande', 10.0, 'Grande', 50.0, 'Não encontrado', 'Arredondada', 2.0, 4.0, 2.0, 'N', 3, true, true, false, 5, 1, 4, 4, 3, 3, false, false, 4, 4, 5, 5, true),
	(120, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780420077801-euxb9ci60rd.jpg', 'Senna fistula (L.) H.S.Irwin & Barneby', 'Cassia imperial', 'Exótica', 'Decídua', 'Set-Dez', 'Out-Jan', 12, 'Médio', NULL, 'Média', NULL, NULL, 'Pendente', 2.5, 4, 4, 'C', 3, true, true, false, 3, 2, 4, 3, 3, 4, false, false, 3, 4, 3, 3, true),
	(105, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/pachira-aquatica-aubl.jpg', 'Pachira aquatica Aubl.', 'Monguba', 'Nativa BR', 'Semidecídua', 'Set-Nov', 'Abr-Jun', 15.0, 'Médio', 10.0, 'Grande', 40.0, '2,0 - 3,0', 'Arredondada', 2.0, 4.0, 12.0, 'N', 4, true, true, false, 2, 5, 3, 2, 2, 4, false, false, 4, 2, 4, 4, true),
	(106, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/pterygota-brasiliensis-allem-o.jpg', 'Pterygota brasiliensis Allemão', 'Pau-rei', 'Nativa BR', 'Perenifólia', 'Jul-Out', 'Nov-Fev', 35.0, 'Grande', 15.0, 'Grande', 80.0, '8 - 12', 'Arredondada / Irregular', 3.0, 3.0, 5.0, 'N', 4, true, true, false, 3, 2, 3, 3, 3, 3, false, false, 4, 2, 5, 5, true),
	(95, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/senna-macranthera.jpg', 'Senna macranthera', 'Aleluia, pau-fava', 'Nativa BR', 'Decídua', 'Dez-Abr', 'Mai-Ago', 6.0, 'Pequeno', 5.0, 'Pequena', 30.0, '1.5-2.5', 'Arredondada', 1.5, 2.0, 0.5, 'C', 2, true, true, false, 4, 2, 4, 4, 3, 3, false, false, 4, 4, 2, 4, true),
	(35, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/callistemon-rigidus.webp', 'Callistemon rigidus', 'Escova-de-garrafa', 'Exótica', 'Perenifólia', 'Set-Nov', 'Nov-Mar', 7.0, 'Pequeno', 5.0, 'Pequena', 30.0, '0,6 - 1,2', 'Globosa', 1.5, 1.0, 1.0, 'C', 2, true, true, false, 3, 1, 3, 2, 2, 2, false, false, 3, 4, 2, 2, false),
	(149, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tabebuia-vellosoi.jpg', 'Tabebuia vellosoi', 'Ipê-amarelo-da-mata', 'Nativa BR', 'Decídua', 'Set-Out', 'Out-Nov', 25.0, 'Grande', 8.0, 'Grande', 70.0, '2,5 - 4,0', 'Arredondada/Globosa', 3.0, 4.0, 12.0, 'N', 4, true, true, false, 3, 1, 3, 2, 3, 3, false, false, 4, 3, 4, 4, true),
	(150, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/handroanthus-umbellatus.jpg', 'Handroanthus umbellatus', 'Ipê-amarelo-do-brejo', 'Nativa BR', 'Semidecídua', 'Set-Nov', 'Dez-Jan', 15.0, 'Médio', 6.0, 'Média', 50.0, '2,0 - 3,5', 'Arredondada', 2.5, 1.5, 6.0, 'A', 3, true, true, false, 2, 5, 3, 3, 3, 2, false, false, 4, 3, 4, 5, true),
	(139, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/eugenia-brasiliensis.jpg', 'Eugenia brasiliensis', 'Grumixama', 'Nativa BR', 'Semidecídua', 'Set-Nov', 'Nov-Dez', 10.0, 'Médio', 7.0, 'Média', 40.0, NULL, 'Arredondada', 2.0, 2.5, 1.0, 'A', 2, true, true, true, 3, 4, 4, 3, 4, 3, false, false, 5, 4, 4, 5, true),
	(8, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774376271218-z8qvc3hemw9.png', 'Luehea divaricata Mart.', 'Açoita-cavalo', 'Nativa BR', 'Decídua', 'Dez-Fev', 'Mai-Ago', 25, 'Grande', 8, 'Grande', 60, '1,8-3,0', 'Arredondada', 0.7, 3, 1.8, 'N', 3, true, true, false, 4, 4, 3, 3, 3, 3, false, false, 4, 4, 5, 4, true),
	(94, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/albizia-hasslerii.webp', 'Albizia hasslerii', 'Farinha seca', 'Nativa BR', 'Decídua', 'Out-Jan', 'Set-Out', 20.0, 'Grande', 10.0, 'Grande', 60.0, '10', 'Arredondada', 2.0, 4.0, 2.0, 'N', 4, true, true, false, 4, 3, 4, 3, 3, 4, false, false, 4, 4, 5, 5, true),
	(96, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/holocalyx-balansae.jpg', 'Holocalyx balansae', 'Alecrim-de-campinas', 'Nativa BR', 'Perenifólia', 'Set-Out', 'Nov-Jan', 25.0, 'Grande', 10.0, 'Grande', 100.0, 'Não encontrado', 'Arredondada', 3.0, 9.0, 2.0, 'N', 3, false, true, true, 4, 2, 3, 3, 3, 2, false, true, 4, 4, 4, 4, true),
	(136, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/ouratea-castaneifolia.jpg', 'Ouratea castaneifolia', 'Folha-de-castanha', 'Nativa BR', 'Perenifólia', 'Out-Nov', 'Dez-Jan', 7.0, 'Pequeno', 3.0, 'Pequena', 20.0, '0,5 - 1,0', 'Globosa', 1.5, 0.8, 2.0, 'C', 2, true, true, false, 3, 3, 3, 3, 3, 2, false, false, 3, 3, 2, 4, true),
	(137, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/allophyllus-edulis.jpg', 'Allophyllus edulis', 'Fruto-de-pombo, murta-branca', 'Nativa BR', 'Semidecídua', 'Set-Nov', 'Nov-Dez', 10.0, 'Médio', NULL, 'Média', 30.0, NULL, 'Arredondada', 2.0, 4.0, 2.0, 'C', 2, true, true, false, 3, 2, 3, 3, 3, 2, false, false, 3, 4, 3, 3, true),
	(99, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/handroanthus-impetiginosus.jpg', 'Handroanthus impetiginosus', 'Ipê-roxo-de-bola', 'Nativa BR', 'Decídua', 'Mai-Ago', 'Set-Out', 35.0, 'Grande', 20.0, 'Grande', 100.0, NULL, 'Arredondada', 4.0, 8.0, 4.0, 'N', 4, true, true, false, 4, 2, 4, 3, 3, 4, false, false, 5, 4, 5, 5, true),
	(104, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/handroanthus-roseo-alba.png', 'Tabebuia roseo-alba', 'Ipê-branco', 'Nativa BR', 'Decídua', 'Ago-Set', 'Out-Dez', 14, 'Médio', 10, 'Média', 50, NULL, 'Arredondada', 2.5, 4, 2, 'A', 2, true, true, false, 4, 2, 3, 3, 3, 4, false, false, 4, 4, 4, 4, true),
	(9, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774376629346-93emv7ltm3s.jpg', 'Pterocarpus violaceus Vogel', 'Aldrago', 'Nativa BR', 'Perenifólia', 'Out-Dez', 'Mai-Jul', 14, 'Médio', NULL, 'Média', 50, '2,5–4,0', 'Arredondada', 2.5, 4, 4, 'A', 3, true, true, false, 4, 2, 3, 3, 3, 2, false, false, 3, 3, 3, 4, true),
	(14, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/hibiscus-pernambucensis.webp', 'Hibiscus pernambucensis', 'Algodão-do-brejo', 'Nativa BR', 'Perenifólia', 'Ago-Jan', 'Fev-Abr', 6, 'Pequeno', 4, 'Pequena', 30, '0,5 - 1,0', 'Irregular', 1.5, 0.8, 2, 'C', 2, true, false, false, 3, 5, 4, 3, 5, 2, false, false, 3, 4, 3, 4, true),
	(107, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/stifftia-crysantha-mikan.jpg', 'Stifftia crysantha Mikan', 'Rabo-de-cutia', 'Nativa BR', 'Perenifólia', 'Jul-Set', 'Set-Nov', 3.5, 'Pequeno', NULL, 'Pequena', 25.0, NULL, 'Arredondada', 2.0, 2.0, NULL, 'C', 1, true, true, false, 3, 3, 4, 3, 3, 2, false, false, 3, 4, 2, 3, true),
	(113, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780419259577-z3t1im5vxm.avif', 'Callistemon imperialis', 'Calistemon', 'Exótica', 'Perenifólia', 'Ano todo', 'Ano todo', 6, 'Pequeno', 5, 'Pequena', 25, '1.5-2.5', 'Pendente', 1, 1, 0.3, 'C', 1, true, true, false, 4, 2, 4, 4, 3, 3, false, false, 4, 5, 2, 3, true),
	(10, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774376693787-bvizx2fy3gm.jpg', 'Pterocarpus rohrii Vahl', 'Aldrago miúdo', 'Nativa BR', 'Perenifólia', 'Out-Dez', 'Mai-Jul', 20.0, 'Grande', 10.0, 'Grande', 80.0, '2,5 - 4,0', 'Arredondada', 3.0, 4.0, 15.0, 'N', 4, true, true, false, 4, 2, 3, 2, 3, 3, false, false, 4, 2, 4, 4, true),
	(17, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/psidium-cattleianum-sabine.jpg', 'Psidium cattleianum Sabine', 'Araçá', 'Nativa BR', 'Perenifólia', 'Jun-Dez', 'Set-Mar', 6.0, 'Pequeno', 5.0, 'Pequena', 30.0, '1.5-2.5', 'Arredondada', 2.0, 2.0, 2.0, 'C', 1, true, true, false, 3, 3, 4, 3, 3, 4, false, false, 4, 4, 3, 4, true),
	(18, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774377129874-bxgztgfuyfb.jpg', 'Andira fraxinifolia', 'Angelim-doce', 'Nativa BR', 'Semidecídua', 'Nov-Fev', 'Mar-Jun', 30.0, 'Grande', 20.0, 'Grande', 120.0, NULL, 'Arredondada', 4.0, 12.0, 6.0, 'N', 4, true, true, false, 4, 2, 3, 3, 3, 3, false, false, 4, 3, 4, 4, true),
	(20, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774377242390-uz6chbas8d9.webp', 'Schinus terebinthifolius', 'Aroeira-pimenteira', 'Nativa BR', 'Perenifólia', 'Nov-Jan', 'Dez-Mar', 15.0, 'Médio', 12.0, 'Média', 60.0, '2-4', 'Arredondada', 2.0, 8.0, 4.0, 'C', 3, true, true, false, 4, 2, 4, 3, 3, 4, false, true, 5, 4, 4, 3, true),
	(97, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/calyptranthes-clusiifolia.jpg', 'Calyptranthes clusiifolia', 'Araçarana', 'Nativa BR', 'Perenifólia', 'Out-Nov', 'Dez-Jan', 5.0, 'Pequeno', 2.5, 'Pequena', 15.0, '0,5 - 1,0', 'Arredondada', 1.5, 0.8, 2.0, 'C', 1, false, true, true, 2, 3, 2, 2, 2, 1, false, false, 4, 2, 2, 4, true),
	(98, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/schinus-terebinthifolia.jpg', 'Schinus terebinthifolia', 'Aroeira-pimenteira', 'Nativa BR', 'Perenifólia', 'Set-Nov', 'Dez-Mar', 15.0, 'Médio', 12.0, 'Média', 60.0, '2-4', 'Arredondada', 2.0, 4.0, 2.0, 'C', 3, true, true, false, 4, 4, 4, 3, 3, 4, false, true, 5, 4, 4, 4, true),
	(115, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780419360397-n23puu9muw.jpg', 'Myrciaria tenella', 'Cambuí', 'Nativa BR', 'Perenifólia', 'Out-Nov', 'Dez-Jan', 6, 'Pequeno', 3, 'Pequena', 20, '0,5 - 1,0', 'Globosa', 1.5, 0.8, 2, 'C', 2, true, true, false, 3, 3, 3, 3, 3, 2, false, false, 5, 3, 2, 5, true),
	(152, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tabebuia-avellanedae-var-paulensis.jpg', 'Tabebuia avellanedae var. paulensis', 'Ipê-roxo-anão', 'Nativa BR', 'Decídua', 'Jun-Ago', 'Ago-Nov', 8.0, 'Médio', 5.0, 'Pequena', 40.0, NULL, 'Arredondada', 1.0, 1.0, 0.5, 'C', 2, true, true, false, 4, 2, 4, 3, 4, 3, false, false, 4, 4, 3, 4, true),
	(7, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774376219138-5vwcwfhw48k.jpg', 'Casearia sylvestris Sw.', 'Guaçatonga', 'Nativa BR', 'Perenifólia', 'Jun-Ago', 'Set-Nov', 6, 'Pequeno', 5, 'Pequena', 30, 'Não encontrado', 'Arredondada', 1.5, 2, 0.8, 'C', 1, true, true, false, 4, 3, 4, 3, 3, 3, false, false, 4, 4, 3, 4, true),
	(15, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/protium-heptaphyllum-aubl-marchand.jpg', 'Protium heptaphyllum (Aubl.) Marchand', 'Almecega', 'Nativa BR', 'Decídua', 'Ago-Set', 'Nov-Dez', 20, 'Grande', 12, 'Média', 60, '2,5-4,0', 'Arredondada', 2, 4, 6, 'A', 3, true, true, false, 3, 4, 3, 3, 3, 3, false, true, 4, 3, 4, 4, false),
	(117, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780420006021-llhmrmogb3h.jpeg', 'Rapanea ferruginea', 'Capororoca', 'Nativa BR', 'Decídua', 'Mai-Jun', 'Out-Dez', 12, 'Médio', NULL, 'Média', 40, NULL, 'Arredondada', 2.5, NULL, 12, 'C', 2, true, true, false, 3, 3, 4, 3, 3, 2, false, false, 4, 4, 3, 4, true),
	(119, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780419307911-hw65vikvy6.JPG', 'Matayba eleagnoides', 'Caqui-do-mato, olho-de-boi', 'Nativa BR', 'Semidecídua', 'Set-Nov', 'Dez-Jan', 14, 'Médio', NULL, 'Média', 50, NULL, 'Arredondada', 2.5, 4, 3, 'A', 2, true, true, false, 3, 4, 3, 3, 3, 3, false, false, 4, 4, 3, 4, true),
	(123, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780420175456-0v6bkt72y4rr.jpg', 'Trichilia claussenii', 'Catiguá vermelho', 'Nativa BR', 'Semidecídua', 'Não encontrado', 'Não encontrado', 20, 'Grande', NULL, 'Grande', 50, 'Não encontrado', 'Arredondada', 3, 25, 5, 'N', 4, true, true, false, 3, 2, 3, 3, 3, 3, false, true, 3, 3, 4, 4, true),
	(134, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/lonchocarpus-guilleminianus.webp', 'Lonchocarpus guilleminianus', 'Falso-timbó, ingá-bravo', 'Nativa BR', 'Semidecídua', 'Dez-Jan', 'Jul-Ago', 20.0, 'Grande', 10.0, 'Grande', 60.0, NULL, 'Arredondada', 4.0, 10.0, 5.0, 'N', 3, true, true, false, 4, 2, 3, 3, 3, 3, false, false, 3, 3, 4, 4, true),
	(141, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780420258070-5soj6ejny8o.jpg', 'Savia dictyocarpa', 'Guaraiuva', 'Nativa BR', 'Semidecídua', 'Não encontrado', 'Não encontrado', 25, 'Grande', 15, 'Média', 60, NULL, 'Arredondada', 2.5, 4, 2, 'A', 2, true, true, false, 3, 3, 3, 3, 3, 2, false, true, 3, 3, 4, 4, true),
	(190, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tapirira-guianensis.jpg', 'Tapirira guianensis', 'Peito-do-pombo', 'Nativa BR', 'Perenifólia', 'Set-Out', 'Jan-Fev', 14.0, 'Médio', 6.0, 'Média', 50.0, '2,0 - 3,5', 'Globosa', 2.5, 1.0, 4.0, 'A', 2, true, true, false, 2, 5, 3, 3, 3, 3, false, false, 5, 3, 4, 5, true),
	(193, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/duguetia-lanceolata.jpg', 'Duguetia lanceolata', 'Pindaiva', 'Nativa BR', 'Perenifólia', 'Set-Out', 'Mar-Mai', 20.0, 'Grande', 5.0, 'Pequena', 60.0, '4,0 - 6,0', 'Piramidal', 2.5, 1.5, 6.0, 'N', 2, false, true, true, 2, 3, 2, 2, 3, 2, false, false, 5, 2, 3, 5, true),
	(151, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tabebuia-pentaphylla.jpg', 'Tabebuia pentaphylla', 'Ipê-rosa', 'Exótica', 'Decídua', 'Ago-Out', 'Set', 20.0, 'Grande', 12.0, 'Grande', 60.0, '2,5 - 3,5', 'Arredondada', 3.5, 1.0, 12.0, 'N', 4, true, true, false, 3, 1, 3, 2, 3, 3, false, false, 3, 3, 4, 3, true),
	(1, 'https://upload.wikimedia.org/wikipedia/commons/0/06/Licania_tomentosa.JPG', 'Licania tomentosa', 'Oiti', 'Nativa BR', 'Perenifólia', 'Jun-Ago', 'Jan-Mar', 15, 'Médio', 10, 'Grande', 50, '2,0 - 3,0', 'Arredondada', 3, 3, 20, 'N', 4, true, true, false, 3, 3, 4, 4, 4, 4, false, false, 4, 4, 5, 4, true),
	(3, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/bauhinia-forficata.jpg', 'Bauhinia forficata', 'Pata-de-vaca', 'Nativa BR', 'Semidecídua', 'Nov-Jan', 'Jul-Ago', 9, 'Médio', 5, 'Média', 40, '1,5 - 2,0', 'Arredondada', 2.5, 2, 10, 'A', 2, true, true, false, 3, 4, 4, 3, 3, 3, true, false, 4, 3, 4, 4, true),
	(73, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/erythrina-speciosa.webp', 'Erythrina speciosa', 'Suinã', 'Nativa BR', 'Decídua', 'Ago-Out', 'Nov-Dez', 6.0, 'Pequeno', 4.0, 'Pequena', 25.0, '1,0 - 1,5', 'Irregular', 1.5, 0.8, 2.0, 'C', 2, true, true, false, 3, 3, 3, 3, 2, 3, true, false, 4, 3, 2, 4, true),
	(76, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780418806390-ox3epvm24c.jpg', 'Callicarpa reevesii', 'Calicarpa', 'Exótica', 'Semidecídua', 'Fev-Abr', 'Não encontrado', 7, 'Pequeno', NULL, 'Pequena', 25, 'Não encontrado', 'Arredondada', 1.5, 2, 2, 'C', 1, true, true, false, 3, 3, 4, 3, 3, 2, false, false, 4, 4, 2, 3, true),
	(108, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/luehea-divaricata.jpg', 'Luehea divaricata', 'Açoita-cavalo', 'Nativa BR', 'Decídua', 'Dez-Abr', 'Abr-Out', 30.0, 'Grande', 10.0, 'Grande', 100.0, '2,5 - 3,5', 'Espalhada', 2.0, 2.0, 12.0, 'N', 4, true, true, false, 3, 2, 3, 2, 3, 3, false, false, 4, 3, 4, 4, true),
	(110, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780418974289-c70o92nzcie.jpg', 'Myrocarpus frondosus', 'Cabreúva-amarela', 'Nativa BR', 'Decídua', 'Mai-Jun (RJ); Ago-Set (PR); Ago-Out (RS)', 'Set-Dez (SP); Nov-Fev (PR); Abr-Mai (ES)', 35, 'Grande', 20, 'Grande', 100, '10-15', 'Irregular', 4, 16, 2, 'N', 3, true, true, false, 3, 2, 3, 3, 3, 3, false, true, 3, 3, 4, 4, true),
	(111, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780418922730-3bj0oyp23mc.jpeg', 'Myroxylon peruiferum L.f.', 'Cabreúva-vermelha', 'Nativa BR', 'Semidecídua', 'Jul-Set', 'Out-Nov', 35, 'Grande', NULL, 'Grande', NULL, '10–12', 'Arredondada', 2, 4, 8, 'N', 4, true, true, false, 3, 2, 3, 2, 3, 2, false, true, 3, 3, 4, 4, true),
	(116, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/peltophorum-dubium.jpg', 'Peltophorum dubium', 'Canafístula', 'Nativa BR', 'Semidecídua', 'Ago-Nov', 'Jul-Set', 25.0, 'Grande', 20.0, 'Grande', 80.0, NULL, 'Arredondada', 3.0, 25.0, 5.0, 'N', 4, true, true, false, 4, 2, 4, 4, 3, 4, false, false, 4, 4, 5, 4, true),
	(118, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/metrodorea-nigra.jpeg', 'Metrodorea nigra', 'Caputuna-preta', 'Nativa BR', 'Semidecídua', 'Set-Nov', 'Dez-Mar', 25.0, 'Grande', 18.0, 'Grande', 90.0, NULL, 'Arredondada', 3.5, 12.0, 36.0, 'N', 3, true, true, false, 5, 1, 3, 4, 4, 3, false, false, 3, 3, 4, 4, true),
	(122, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/trichilia-hirta-l.jpg', 'Trichilia hirta L.', 'Catiguá', 'Nativa BR', 'Semidecídua', 'Jul-Set', 'Mai-Jul', 14.0, 'Médio', 7.0, 'Média', 30.0, 'Não encontrado', 'Arredondada', 2.0, 4.0, 1.5, 'A', 2, true, true, false, 3, 4, 4, 3, 3, 3, false, false, 4, 4, 4, 4, true),
	(125, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/hexachlamys-edulis.jpg', 'Hexachlamys edulis', 'Cerejeira-do-rio-grande', 'Nativa BR', 'Decídua', 'Set-Nov', 'Nov-Dez', 6.0, 'Pequeno', 6.0, 'Média', 30.0, '1,5-2,5', 'Arredondada', 2.0, 2.0, 1.0, 'C', 2, true, true, false, 3, 2, 3, 3, 3, 3, false, false, 4, 3, 3, 4, true),
	(127, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/copaifera-langsdorffii.jpg', 'Copaifera langsdorffii', 'Copaíba', 'Nativa BR', 'Semidecídua', 'Nov-Mar', 'Jul-Set', 35.0, 'Grande', 20.0, 'Grande', 100.0, '12', 'Arredondada', 3.0, 8.0, 20.0, 'N', 4, true, true, false, 4, 3, 3, 4, 3, 3, false, true, 4, 3, 4, 4, true),
	(129, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/couroupita-guianensis.jpg', 'Couroupita guianensis', 'Corrupita, abricó-de-macaco', 'Nativa BR', 'Perenifólia', 'Ano todo', 'Ano todo', 20.0, 'Grande', 10.0, 'Grande', 100.0, '3,0 - 5,0', 'Arredondada', 4.0, 3.0, 15.0, 'N', 5, true, false, false, 2, 3, 3, 2, 3, 5, false, false, 5, 2, 5, 5, true),
	(130, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780420215481-5la6e0bsvp7.jpg', 'Syzygium aromaticum', 'Craveiro-da-índia', 'Exótica', 'Perenifólia', 'Set-Nov', 'Dez-Fev', 10, 'Médio', 4, 'Média', 30, '0,5 - 1,5', 'Piramidal', 2, 1, 4, 'A', 2, true, true, false, 2, 3, 2, 2, 2, 2, false, false, 4, 3, 3, 2, true),
	(131, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/lafoensia-pacari.jpg', 'Lafoensia pacari', 'Dedaleira', 'Nativa BR', 'Decídua', 'Out-Dez', 'Abr-Jun', 25.0, 'Grande', 15.0, 'Grande', 60.0, '10', 'Arredondada', 3.0, 9.0, 3.0, 'N', 4, true, true, false, 4, 3, 4, 4, 3, 3, false, false, 4, 4, 5, 4, true),
	(132, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/lonchocarpus-muehlbergianus.jpg', 'Lonchocarpus muehlbergianus', 'Embira-de-sapo, feijão cru', 'Nativa BR', 'Decídua', 'Out-Jan', 'Jul-Ago', 15.0, 'Médio', 8.0, 'Média', 40.0, '2,5 - 3,5', 'Arredondada', 1.0, 1.0, 8.0, 'A', 3, true, true, false, 4, 1, 3, 2, 3, 3, false, true, 4, 3, 3, 4, true),
	(133, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/murraya-paniculata.jpg', 'Murraya paniculata', 'Falsa murta', 'Exótica', 'Perenifólia', 'Out-Jan', 'Fev-Mai', 6.0, 'Pequeno', 5.0, 'Pequena', 20.0, NULL, 'Arredondada', 1.0, 1.0, 0.5, 'C', 2, true, true, false, 3, 3, 5, 4, 3, 3, false, false, 3, 5, 3, 2, true),
	(138, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/genipa-americana.jpg', 'Genipa americana', 'Genipapo', 'Nativa BR', 'Semidecídua', 'Nov-Mar', 'Fev-Abr', 30.0, 'Grande', 10.0, 'Grande', 90.0, NULL, 'Arredondada', 4.0, 9.0, 2.0, 'N', 4, true, true, false, 2, 5, 3, 3, 3, 4, false, true, 5, 3, 5, 5, true),
	(140, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/casearia-sylvestris.jpg', 'Casearia sylvestris', 'Guaçatonga', 'Nativa BR', 'Perenifólia', 'Jun-Ago', 'Set-Nov', 6, 'Pequeno', 10, 'Pequena', 30, 'Não encontrado', 'Arredondada', 2, NULL, NULL, 'C', 1, true, true, false, 4, 3, 3, 3, 3, 3, false, false, 3, 4, 2, 3, true),
	(142, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/esenbeckia-leiocarpa.jpg', 'Esenbeckia leiocarpa', 'Guarantã', 'Nativa BR', 'Semidecídua', 'Set-Jan', 'Jul-Ago', 30.0, 'Grande', 20.0, 'Grande', 80.0, NULL, 'Arredondada', 3.0, 9.0, 1.5, 'N', 3, true, true, false, 2, 3, 4, 3, 3, 2, false, false, 3, 4, 5, 4, true),
	(156, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/dalbergia-nigra.webp', 'Dalbergia nigra', 'Jacarandá-da-Bahia', 'Nativa BR', 'Semidecídua', 'Set-Nov', 'Ago-Set', 20.0, 'Grande', 15.0, 'Grande', 45.0, NULL, 'Arredondada', 3.0, 4.0, 2.0, 'N', 4, true, true, false, 3, 2, 3, 3, 3, 3, false, false, 3, 3, 5, 4, true),
	(153, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tabebuia-impetiginosa.jpeg', 'Tabebuia impetiginosa', 'Ipê-roxo-de-bola', 'Nativa BR', 'Decídua', 'Mai-Ago', 'Set-Out', 30.0, 'Grande', 15.0, 'Grande', 100.0, NULL, 'Arredondada', 3.0, 25.0, 5.0, 'N', 3, true, true, false, 4, 2, 4, 3, 3, 4, false, false, 4, 4, 4, 5, true),
	(86, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/stifftia-crysantha.jpg', 'Stifftia crysantha', 'Rabo-de-cutia', 'Nativa BR', 'Perenifólia', 'Jul-Set', 'Set-Nov', 3.5, 'Pequeno', 5.0, 'Pequena', 20.0, NULL, 'Arredondada', 1.5, 2.25, 0.5, 'C', 1, true, true, true, 4, 2, 4, 3, 3, 2, false, false, 3, 3, 2, 3, true),
	(145, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tabebuia-chrysotricha.jpg', 'Tabebuia chrysotricha', 'Ipê-amarelo', 'Nativa BR', 'Decídua', 'Ago-Set', 'Out-Nov', 10.0, 'Médio', 5.0, 'Pequena', 40.0, '2,0 - 3,0', 'Arredondada', 1.0, 1.0, 3.0, 'C', 2, true, true, false, 3, 1, 3, 2, 2, 2, false, false, 4, 3, 3, 4, true),
	(16, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1774377060092-9t0i2xveann.jpg', 'Helietta apiculata', 'Amarelinho', 'Nativa BR', 'Semidecídua', 'Nov-Dez', 'Mar-Mai', 18.0, 'Grande', NULL, 'Média', 50.0, NULL, 'Arredondada', 2.5, 4.0, 3.0, 'A', 2, true, true, false, 3, 3, 3, 3, 3, 3, false, false, 3, 4, 3, 4, true),
	(146, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tabebuia-aurea.jpg', 'Tabebuia aurea', 'Ipê-amarelo', 'Nativa BR', 'Perenifólia', 'Ago-Set', 'Out-Nov', 14.0, 'Médio', 6.0, 'Média', 50.0, '2,0 - 3,0', 'Arredondada', 1.5, 1.0, 1.0, 'A', 3, true, false, false, 4, 1, 3, 2, 4, 2, false, false, 4, 3, 4, 4, true),
	(89, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780420118323-ptu0zeu7aaf.jpeg', 'Trichilia claussenii C.DC.', 'Catiguá vermelho', 'Nativa BR', 'Semidecídua', 'Ago-Out', 'Jan-Mar', 14, 'Médio', 7, 'Média', 30, 'Não encontrado', 'Arredondada', 2, 4, 1.5, 'A', 2, true, true, true, 3, 4, 4, 3, 3, 3, false, false, 4, 4, 4, 4, true),
	(143, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/astronium-graveolens.jpg', 'Astronium graveolens', 'Guaritá', 'Nativa BR', 'Decídua', 'Jun-Out', 'Set-Nov', 30.0, 'Grande', 10.0, 'Média', 100.0, '15-20', 'Arredondada', 3.0, 9.0, 1.0, 'N', 4, true, true, false, 4, 2, 3, 3, 3, 2, false, false, 3, 3, 3, 4, true),
	(144, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/inga-uruguensis.jpg', 'Inga uruguensis', 'Ingá do brejo', 'Nativa BR', 'Perenifólia', 'Ago-Nov', 'Dez-Fev', 15.0, 'Médio', 8.0, 'Média', 40.0, '2,0 - 3,0', 'Arredondada', 1.0, 1.0, 3.0, 'A', 3, true, true, false, 2, 4, 3, 2, 2, 3, false, false, 4, 3, 4, 4, true),
	(154, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tabebuia-heptaphylla.jpg', 'Tabebuia heptaphylla', 'Ipê-roxo', 'Nativa BR', 'Decídua', 'Mai-Jul', 'Ago-Set', 35.0, 'Grande', 20.0, 'Grande', 150.0, NULL, 'Arredondada', 2.5, 5.0, 2.0, 'N', 4, true, true, false, 4, 2, 3, 3, 3, 3, false, false, 3, 4, 4, 4, true),
	(155, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/machaerium-villosum.jpg', 'Machaerium villosum', 'Jacarandá paulista', 'Nativa BR', 'Decídua', 'Out-Dez', 'Ago-Set', 25.0, 'Grande', 12.0, 'Grande', 80.0, NULL, 'Arredondada', 4.0, 10.0, 5.0, 'N', 3, true, true, false, 4, 2, 3, 3, 3, 3, false, false, 3, 3, 4, 4, false),
	(162, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/cariniana-legalis-mart-kuntze.jpg', 'Cariniana legalis (Mart.) Kuntze', 'Jequitibá rosa', 'Nativa BR', 'Decídua', 'Dez-Fev', 'Ago-Set', 60.0, 'Grande', 20.0, 'Grande', 400.0, '15-20', 'Arredondada/Globosa', NULL, 4.0, 30.0, 'N', 5, true, true, false, 2, 2, 2, 2, 4, 3, false, false, 5, 2, 5, 5, true),
	(163, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/lophanthera-lactescens.jpg', 'Lophanthera lactescens', 'Lofântera', 'Nativa BR', 'Perenifólia', 'Set-Out', 'Dez-Fev', 20.0, 'Grande', 6.0, 'Média', 40.0, '2,0 - 3,0', 'Arredondada', 2.5, 2.25, 10.0, 'A', 2, true, true, false, 2, 5, 3, 2, 3, 2, false, false, 4, 3, 4, 4, true),
	(164, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/cordia-trichotoma.jpg', 'Cordia trichotoma', 'Louro pardo', 'Nativa BR', 'Decídua', 'Abr-Jul', 'Jul-Set', 30.0, 'Grande', 10.0, 'Grande', 90.0, '3,0 - 5,0', 'Arredondada', 3.5, 4.0, 20.0, 'N', 3, true, true, false, 4, 2, 3, 3, 3, 3, false, false, 3, 3, 4, 4, true),
	(165, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/magnolia-grandiflora.jpg', 'Magnolia grandiflora', 'Magnólia', 'Exótica', 'Perenifólia', 'Out-Dez', 'Jan-Mar', 20.0, 'Grande', 8.0, 'Grande', 80.0, '2,0 - 3,0', 'Piramidal', 3.0, 4.0, 20.0, 'N', 4, true, true, false, 2, 2, 3, 2, 3, 2, false, false, 3, 2, 5, 3, true),
	(189, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/luetzelburgia-auriculata.jpg', 'Luetzelburgia auriculata', 'Pau-ripa', 'Nativa BR', 'Semidecídua', 'Dez-Fev', 'Mar-Mai', 22.0, 'Grande', 12.0, 'Grande', 70.0, '3,0-4,0', 'Arredondada', NULL, NULL, 15.0, 'N', 4, true, true, false, 3, 2, 3, 2, 3, 2, false, false, 3, 2, 5, 4, true),
	(147, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tabebuia-ochracea.jpg', 'Tabebuia ochracea', 'Ipê-amarelo', 'Nativa BR', 'Decídua', 'Ago-Out', 'Out-Nov', 14.0, 'Médio', 6.0, 'Média', 50.0, '2,0 - 3,0', 'Arredondada', 1.5, 1.0, 3.0, 'A', 3, true, true, false, 4, 2, 3, 2, 3, 2, false, false, 4, 3, 4, 4, true),
	(148, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tabebuia-serratifolia.jpg', 'Tabebuia serratifolia', 'Ipê-amarelo', 'Nativa BR', 'Decídua', 'Ago-Out', 'Out-Nov', 20.0, 'Grande', 10.0, 'Grande', 80.0, '3,0 - 4,0', 'Arredondada', 2.0, 2.0, 6.0, 'N', 4, true, true, false, 4, 2, 4, 2, 3, 3, false, false, 4, 3, 5, 4, true),
	(90, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/inga-aurita.jpg', 'Inga aurita', 'Ingá-orelha', 'Nativa BR', 'Perenifólia', 'Não encontrado', 'Não encontrado', 15.0, 'Médio', 12.0, 'Média', 60.0, 'Não encontrado', 'Arredondada', 2.5, 4.0, 1.0, 'A', 3, true, true, false, 3, 4, 3, 3, 3, 4, false, false, 5, 4, 4, 4, false),
	(176, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/ceiba-speciosa.jpg', 'Ceiba speciosa', 'Paineira', 'Nativa BR', 'Decídua', 'Jan-Mai', 'Ago-Out', 20.0, 'Grande', 12.0, 'Grande', 100.0, '3,0 - 6,0', 'Arredondada', 3.0, 3.0, 25.0, 'N', 5, true, false, false, 4, 2, 4, 3, 3, 4, true, false, 5, 2, 5, 5, true),
	(159, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/hymenaea-courbaril-l.jpg', 'Hymenaea courbaril L.', 'Jatobá', 'Nativa BR', 'Semidecídua', 'Set-Nov', 'Jun-Dez', 35.0, 'Grande', 12.0, 'Grande', 120.0, '2,5 - 3,5', 'Arredondada', 2.0, 4.0, 12.0, 'N', 4, true, true, false, 4, 2, 3, 2, 3, 4, false, true, 5, 2, 5, 5, true),
	(170, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/melaleuca-leucadendron.jpg', 'Melaleuca leucadendron', 'Melaleuca', 'Exótica', 'Perenifólia', 'Ago-Out', 'Nov-Jan', 15.0, 'Médio', 6.0, 'Média', 50.0, '2,0 - 3,0', 'Arredondada', 2.5, 2.0, 10.0, 'A', 3, true, true, false, 3, 5, 4, 4, 4, 3, false, true, 3, 4, 3, 2, true),
	(171, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/lafoensia-glyptocarpa.jpg', 'Lafoensia glyptocarpa', 'Mirindiba', 'Nativa BR', 'Semidecídua', 'Nov-Jan', 'Fev-Abr', 20.0, 'Grande', 8.0, 'Grande', 60.0, '3,0 - 4,0', 'Arredondada', 3.0, 3.0, 20.0, 'N', 3, true, true, false, 3, 4, 3, 3, 3, 3, false, false, 4, 2, 5, 4, true),
	(173, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/erythrina-mulungu.jpg', 'Erythrina mulungu', 'Mulungu', 'Nativa BR', 'Decídua', 'Ago-Out', 'Out-Dez', 12.0, 'Médio', 6.0, 'Média', 50.0, '1,5 - 2,5', 'Arredondada', 2.5, 2.0, 10.0, 'A', 3, true, true, false, 4, 3, 3, 3, 3, 3, true, false, 5, 2, 4, 5, true),
	(160, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/hymenaea-stigonocarpa.webp', 'Hymenaea stigonocarpa', 'Jatobá-do-cerrado', 'Nativa BR', 'Semidecídua', 'Ago-Out', 'Nov-Jan', 10.0, 'Médio', 6.0, 'Média', 60.0, '2,0 - 4,0', 'Arredondada', 2.5, 1.5, 6.0, 'A', 3, true, false, false, 5, 1, 3, 2, 4, 3, false, false, 4, 3, 4, 5, true),
	(175, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/ormosia-arborea.jpg', 'Ormosia arborea', 'Olho-de-cabra', 'Nativa BR', 'Perenifólia', 'Out-Dez', 'Ago-Out', 20.0, 'Grande', 10.0, 'Grande', 70.0, '3,0 - 5,0', 'Arredondada', 3.0, 3.0, 20.0, 'N', 3, true, true, false, 3, 3, 3, 3, 3, 2, false, false, 5, 2, 5, 5, true),
	(157, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/syzygium-jambos-l-alston.jpg', 'Syzygium jambos (L.) Alston', 'Jambo amarelo', 'Exótica', 'Perenifólia', 'Jul-Nov', 'Dez-Abr', 12.0, 'Médio', 7.0, 'Média', 60.0, NULL, 'Arredondada', 3.4, 4.0, 4.0, 'A', 2, true, true, false, 3, 3, 4, 3, 3, 4, false, false, 4, 4, 4, 3, true),
	(158, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/syzygium-malaccense.jpg', 'Syzygium malaccense', 'Jambo vermelho', 'Exótica', 'Perenifólia', 'Ago-Fev', 'Jan-Mai', 12.0, 'Médio', 7.0, 'Média', NULL, 'Não encontrado', 'Piramidal', 1.5, 2.25, 1.0, 'A', 2, true, true, false, 2, 3, 4, 3, 3, 4, false, false, 4, 4, 4, 3, true),
	(161, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/cariniana-estrellensis.jpg', 'Cariniana estrellensis', 'Jequitibá branco', 'Nativa BR', 'Semidecídua', 'Out-Dez', 'Jul-Set', 35.0, 'Grande', 25.0, 'Grande', 80.0, '15-20', 'Arredondada', 4.0, 16.0, 8.0, 'N', 4, true, true, false, 3, 3, 3, 2, 4, 3, false, false, 4, 4, 5, 5, true),
	(191, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/aspidosperma-cylindrocarpon.jpg', 'Aspidosperma cylindrocarpon', 'Peroba poca', 'Nativa BR', 'Semidecídua', 'Ago-Out', 'Out-Nov', 25.0, 'Grande', 10.0, 'Grande', 80.0, '3,0 - 5,0', 'Arredondada', 3.0, 2.25, 10.0, 'N', 3, true, true, false, 4, 2, 3, 3, 4, 2, false, true, 3, 2, 5, 4, true),
	(192, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/aspidosperma-polyneuron.jpg', 'Aspidosperma polyneuron', 'Peroba rosa', 'Nativa BR', 'Semidecídua', 'Set-Out', 'Out-Dez', 30.0, 'Grande', 12.0, 'Grande', 100.0, '5,0 - 10,0', 'Arredondada', 3.5, 2.25, 15.0, 'N', 2, true, true, false, 4, 2, 3, 3, 5, 2, false, true, 3, 2, 5, 5, true),
	(184, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/caesalpinia-echinata.jpg', 'Caesalpinia echinata', 'Pau-brasil', 'Nativa BR', 'Decídua', 'Set-Out', 'Nov-Jan', 12.0, 'Médio', 7.0, 'Média', 70.0, '2,0 - 3,0', 'Arredondada', 2.5, 4.0, 1.0, 'A', 3, true, true, false, 4, 1, 3, 2, 3, 3, false, false, 4, 3, 3, 4, true),
	(185, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/vochysia-tucanorum.jpg', 'Vochysia tucanorum', 'Pau-de-tucano', 'Nativa BR', 'Decídua', 'Nov-Jan', 'Ago-Set', 12.0, 'Médio', 7.0, 'Média', 40.0, '2,0 - 3,0', 'Arredondada', 2.5, 2.0, 2.0, 'A', 2, true, true, false, 4, 1, 3, 2, 3, 2, false, false, 4, 3, 3, 4, true),
	(186, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/caesalpinia-leiostachya.jpg', 'Caesalpinia leiostachya', 'Pau-ferro', 'Nativa BR', 'Decídua', 'Out-Fev', 'Jul-Out', 20.0, 'Grande', 10.0, 'Grande', 80.0, '2,5 - 3,5', 'Arredondada', 3.5, 4.0, 4.0, 'N', 3, true, false, false, 4, 2, 4, 3, 4, 3, false, false, 3, 3, 4, 3, true),
	(71, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/caesalpinia-peltophoroides.webp', 'Caesalpinia peltophoroides', 'Sibipiruna', 'Nativa BR', 'Semidecídua', 'Set-Out', 'Nov-Jan', 20.0, 'Grande', 10.0, 'Grande', 80.0, '3,0 - 5,0', 'Arredondada', 3.0, 2.25, 12.0, 'N', 4, true, false, false, 4, 2, 4, 4, 3, 3, false, false, 3, 3, 5, 4, true),
	(72, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/clitoria-fairchildiana.jpg', 'Clitoria fairchildiana', 'Sombreiro', 'Nativa BR', 'Perenifólia', 'Set-Nov', 'Dez-Mar', 15.0, 'Médio', 8.0, 'Grande', 60.0, '1,5 - 2,5', 'Arredondada', 2.5, 1.5, 6.0, 'A', 2, true, true, false, 3, 3, 4, 3, 3, 2, false, false, 3, 4, 5, 4, true),
	(75, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/lecythis-pisonis.jpg', 'Lecythis pisonis', 'Sapucaia', 'Nativa BR', 'Semidecídua', 'Set-Out', 'Ago-Set', 30.0, 'Grande', 20.0, 'Grande', 100.0, NULL, 'Arredondada', 3.0, 4.0, 2.0, 'N', 5, true, true, false, 2, 4, 3, 3, 4, 5, false, false, 5, 3, 5, 5, true),
	(187, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/platycyamus-regnellii.jpg', 'Platycyamus regnellii', 'Pau-pereira', 'Nativa BR', 'Semidecídua', 'Dez-Fev', 'Jun-Ago', 20.0, 'Grande', 10.0, 'Média', 60.0, '2,0-3,0', 'Arredondada', NULL, NULL, 10.0, 'N', 3, true, true, false, 4, 2, 3, 3, 3, 3, false, false, 3, 3, 4, 4, true),
	(188, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/pterygota-brasiliensis.jpg', 'Pterygota brasiliensis', 'Pau-rei', 'Nativa BR', 'Semidecídua', 'Out-Dez', 'Ago-Out', 30.0, 'Grande', 15.0, 'Grande', 80.0, '3,0-5,0', 'Arredondada', NULL, NULL, 15.0, 'N', 4, true, true, false, 2, 2, 3, 2, 3, 3, false, false, 4, 2, 5, 5, true),
	(70, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/pera-glabrata.jpg', 'Pera glabrata', 'Sapateiro, tobocuva', 'Nativa BR', 'Perenifólia', 'Set-Out', 'Nov-Dez', 10.0, 'Médio', 5.0, 'Média', 40.0, '2,0 - 3,0', 'Arredondada', 2.0, 1.0, 4.0, 'A', 2, true, true, false, 4, 2, 2, 3, 3, 2, false, false, 4, 2, 3, 5, true),
	(91, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tabebuia-avellanedae.jpg', 'Tabebuia avellanedae', 'Ipê-roxo-da-mata', 'Nativa BR', 'Decídua', 'Jul-Ago', 'Jun-Ago', 35.0, 'Grande', 15.0, 'Grande', 80.0, NULL, 'Arredondada', 3.0, 4.0, 2.0, 'N', 4, true, true, false, 4, 2, 4, 3, 4, 3, false, false, 4, 4, 5, 4, true),
	(78, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/balfourodendron-riedelianum.jpg', 'Balfourodendron riedelianum', 'Pau-marfim', 'Nativa BR', 'Semidecídua', 'Set-Nov', 'Ago-Set', 35.0, 'Grande', 20.0, 'Grande', 100.0, '10-15', 'Arredondada', 2.5, 4.0, 8.0, 'N', 3, true, true, false, 4, 2, 3, 3, 4, 2, false, false, 3, 3, 5, 4, true),
	(93, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/ligustrum-lucidum.jpg', 'Ligustrum lucidum', 'Alfeneiro-do-japão', 'Exótica', 'Perenifólia', 'Out-Fev', 'Mai-Ago', 12.0, 'Médio', 7.0, 'Média', 50.0, NULL, 'Arredondada', 2.5, 4.0, 8.0, 'A', 3, true, true, true, 3, 3, 4, 4, 3, 3, false, false, 4, 5, 4, 2, true),
	(92, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/qualea-parviflora.jpg', 'Qualea parviflora', 'Pau-terra-mirim', 'Nativa BR', 'Semidecídua', 'Nov-Dez', 'Set-Out', 10.0, 'Médio', 8.0, 'Média', 30.0, NULL, 'Arredondada', 2.0, 2.5, 1.2, 'A', 3, true, true, false, 5, 2, 3, 4, 3, 3, false, false, 3, 3, 3, 4, true),
	(82, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/platypodium-elegans.jpeg', 'Platypodium elegans', 'Amendoim-do-campo', 'Nativa BR', 'Perenifólia', 'Set-Nov', 'Set-Out', 30.0, 'Grande', 20.0, 'Grande', 60.0, NULL, 'Arredondada', 3.0, 9.0, 2.0, 'N', 4, true, true, false, 4, 3, 3, 3, 3, 3, false, false, 3, 2, 4, 4, true),
	(77, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/cupania-vernalis.jpg', 'Cupania vernalis', 'Camboatá', 'Nativa BR', 'Semidecídua', 'Mar-Mai', 'Set-Dez', 22, 'Grande', 18, 'Grande', 70, NULL, 'Arredondada', 3, 9, 2, 'N', 4, true, true, false, 3, 4, 3, 3, 3, 4, false, false, 5, 3, 4, 4, true),
	(79, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780418856378-lz8s91s072j.webp', 'Senna fistula', 'Cassia imperial', 'Exótica', 'Decídua', 'Set-Dez', 'Out-Jan', 15, 'Médio', 12, 'Média', 60, NULL, 'Arredondada', 2.5, NULL, NULL, 'C', 3, true, true, false, 3, 2, 4, 3, 3, 4, false, false, 4, 4, 4, 3, true),
	(80, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/pterocarpus-rohrii.jpg', 'Pterocarpus rohrii', 'Aldrago miúdo', 'Nativa BR', 'Semidecídua', 'Out-Dez', 'Mai-Jul (seco)', 12.0, 'Médio', 7.0, 'Média', 40.0, NULL, 'Arredondada', 2.5, 4.0, 1.0, 'A', 2, true, true, false, 4, 2, 3, 3, 3, 3, false, false, 4, 4, 4, 4, true),
	(81, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/endlicheria-paniculata.jpg', 'Endlicheria paniculata', 'Canela cheirosa', 'Nativa BR', 'Semidecídua', 'Jan-Mar', 'Mai-Jul', 12.0, 'Médio', 7.0, 'Média', 40.0, NULL, 'Arredondada', 2.5, 3.0, 1.5, 'A', 2, true, true, false, 2, 4, 4, 3, 3, 3, false, false, 4, 4, 4, 4, true),
	(83, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780419401730-hzjpf41pjkm.jpg', 'Ocotea odorifera', 'Canela sassafrás', 'Nativa BR', 'Perenifólia', 'Nov-Dez', 'Jul-Set', 40, 'Grande', 20, 'Grande', NULL, '10-15', 'Arredondada', 4, 16, 40, 'N', 3, true, true, true, 2, 3, 3, 3, 3, 3, false, false, 4, 3, 4, 5, true),
	(84, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780420032922-jst35r24qvd.jpg', 'Rapanea ferruginea Aubl. Mez', 'Capororoca', 'Nativa BR', 'Decídua', 'Mai-Jun', 'Out-Dez', 12, 'Médio', 7, 'Média', 40, 'Não encontrado', 'Arredondada', 2, 4, 1.5, 'A', 2, true, true, false, 4, 3, 4, 3, 3, 3, false, false, 4, 4, 4, 4, true),
	(85, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/myrsine-guianensis.jpg', 'Myrsine guianensis', 'Capororoca-do-cerrado', 'Nativa BR', 'Perenifólia', 'Ano todo (pico Verão)', 'Ano todo', 20.0, 'Grande', 15.0, 'Média', 80.0, NULL, 'Arredondada', 3.0, 9.0, 27.0, 'N', 2, true, true, true, 3, 3, 3, 4, 3, 2, false, false, 4, 4, 4, 4, true),
	(87, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/protium-heptaphyllum.jpg', 'Protium heptaphyllum', 'Almecega', 'Nativa BR', 'Decídua', 'Ago-Set', 'Nov-Dez', 20.0, 'Grande', 15.0, 'Grande', 60.0, '5-10', 'Arredondada', 3.0, 9.0, 2.0, 'N', 4, true, true, false, 3, 4, 3, 3, 3, 3, false, true, 5, 3, 5, 4, true),
	(88, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/1780419478863-i6kxbddlx7s.JPG', 'Ocotea velutina (Nees) Rohwer', 'Canela amarela', 'Nativa BR', 'Semidecídua', 'Abr-Mai', 'Set-Out', 25, 'Grande', 15, 'Grande', 70, 'Não encontrado', 'Arredondada', 3, 9, 4.5, 'N', 4, true, true, false, 3, 2, 3, 3, 3, 3, false, false, 4, 3, 5, 4, true),
	(166, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/michelia-champaca.webp', 'Michelia champaca', 'Magnólia amarela', 'Exótica', 'Perenifólia', 'Set-Nov', 'Dez-Mar', 25.0, 'Grande', 10.0, 'Grande', 80.0, '2,5 - 4,0', 'Piramidal', 3.5, 4.0, 25.0, 'N', 4, true, true, false, 2, 2, 3, 2, 3, 3, false, false, 4, 2, 5, 3, true),
	(167, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tibouchina-mutabilis.jpg', 'Tibouchina mutabilis', 'Manacá-da-serra', 'Nativa BR', 'Semidecídua', 'Dez-Mar', 'Jun-Ago', 12.0, 'Médio', 6.0, 'Média', 40.0, '1,5 - 2,5', 'Arredondada', 2.5, 2.0, 10.0, 'A', 2, true, true, false, 2, 3, 3, 3, 3, 3, false, false, 4, 3, 4, 4, true),
	(194, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/magnolia-ovata-syn-talauma-ovata.webp', 'Magnolia ovata (syn. Talauma ovata)', 'Pinha-do-brejo', 'Nativa BR', 'Perenifólia', 'Set-Out', 'Dez-Fev', 15.0, 'Médio', 6.0, 'Média', 50.0, '2,5 - 4,0', 'Globosa', 2.5, 1.5, 6.0, 'A', 2, false, true, true, 1, 5, 2, 2, 3, 2, false, false, 4, 2, 4, 5, true),
	(195, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/tibouchina-granulosa.jpg', 'Tibouchina granulosa', 'Quaresmeira', 'Nativa BR', 'Perenifólia', 'Jan-Mar e Jun-Ago', 'Abr-Mai e Set-Nov', 12.0, 'Médio', 5.0, 'Média', 40.0, '1,5 - 2,5', 'Globosa', 2.0, 1.0, 4.0, 'A', 2, true, true, false, 3, 3, 4, 3, 3, 3, false, false, 3, 4, 4, 4, true),
	(196, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/koelreuteria-paniculata.jpg', 'Koelreuteria paniculata', 'Quereltéria', 'Exótica', 'Decídua', 'Out-Nov', 'Dez-Jan', 8.0, 'Médio', 4.0, 'Pequena', 30.0, '1,5 - 2,0', 'Arredondada', 1.5, 0.8, 2.0, 'C', 2, true, true, false, 4, 2, 4, 4, 4, 3, false, false, 2, 3, 3, 2, true),
	(197, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/qualea-jundiahy.jpeg', 'Qualea jundiahy', 'Pau-terra, jundiaí', 'Nativa BR', 'Semidecídua', 'Out-Dez', 'Fev-Abr', 25.0, 'Grande', 8.0, 'Grande', 70.0, '4,0 - 7,0', 'Arredondada', 3.0, 2.25, 12.0, 'N', 2, true, true, false, 4, 2, 2, 2, 4, 2, false, false, 3, 2, 4, 4, true),
	(198, 'https://lztvpshdelwdmamtaizu.supabase.co/storage/v1/object/public/tree-images/images/lagerstroemia-speciosa.jpg', 'Lagerstroemia speciosa', 'Resedá de folha graúda', 'Exótica', 'Semidecídua', 'Dez-Fev', 'Mar-Mai', 15.0, 'Médio', 7.0, 'Média', 50.0, '1,5 - 2,5', 'Arredondada', 2.5, 1.5, 6.0, 'A', 4, true, false, false, 3, 4, 4, 3, 2, 3, false, false, 3, 3, 4, 2, true);


--
-- Name: trees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"public"."trees_id_seq"', 198, true);


--
-- PostgreSQL database dump complete
--

-- \unrestrict 8Zqmb4jrv1POfM7JqdNoPpX3FpX3Z6hCKzRo9zqZuAYwmY8ItFFUrlt2JdqZjUg

RESET ALL;
