UPDATE trees SET nome_popular = 'Resedá extremosa' WHERE id = 2;
UPDATE trees SET nome_popular = 'Sabão-de-soldado' WHERE id = 4;
UPDATE trees SET nome_popular = 'Uvaia' WHERE id = 5;
UPDATE trees SET nome_popular = 'Guaçatonga' WHERE id = 7;
UPDATE trees SET nome_popular = 'Açoita-cavalo' WHERE id = 8;
UPDATE trees SET nome_popular = 'Aldrago miúdo' WHERE id = 10;
UPDATE trees SET nome_popular = 'Alfeneiro-do-japão' WHERE id = 12;
UPDATE trees SET nome_popular = 'Algodão-do-brejo' WHERE id = 14;
UPDATE trees SET nome_popular = 'Almecega' WHERE id = 15;
UPDATE trees SET nome_popular = 'Araçá' WHERE id = 17;
UPDATE trees SET nome_popular = 'Angelim-doce' WHERE id = 18;
UPDATE trees SET nome_popular = 'Aroeira-pimenteira' WHERE id = 20;
UPDATE trees SET nome_popular = 'Ipê roxo de bola' WHERE id = 23;
UPDATE trees SET nome_popular = 'Pitangueira' WHERE id = 25;
UPDATE trees SET nome_popular = 'Sapateiro, tobocuva' WHERE id = 70;
UPDATE trees SET nome_popular = 'Suinã' WHERE id = 73;
UPDATE trees SET nome_popular = 'Tarumã-do-cerrado' WHERE id = 74;
UPDATE trees SET nome_popular = 'Calicarpa' WHERE id = 76;
UPDATE trees SET nome_popular = 'Cassia imperial' WHERE id = 79;
UPDATE trees SET nome_popular = 'Aldrago miúdo' WHERE id = 80;
UPDATE trees SET nome_popular = 'Canela cheirosa' WHERE id = 81;
UPDATE trees SET nome_popular = 'Canela sassafrás' WHERE id = 83;
UPDATE trees SET nome_popular = 'Capororoca' WHERE id = 84;
UPDATE trees SET nome_popular = 'Capororoca-do-cerrado' WHERE id = 85;
UPDATE trees SET nome_popular = 'Almecega' WHERE id = 87;
UPDATE trees SET nome_popular = 'Canela amarela' WHERE id = 88;
UPDATE trees SET nome_popular = 'Catiguá vermelho' WHERE id = 89;
UPDATE trees SET nome_popular = 'Ipê roxo da mata' WHERE id = 91;
UPDATE trees SET nome_popular = 'Alecrim-de-campinas' WHERE id = 96;
UPDATE trees SET nome_popular = 'Araçarana' WHERE id = 97;
UPDATE trees SET nome_popular = 'Aroeira-pimenteira' WHERE id = 98;
UPDATE trees SET nome_popular = 'Ipê roxo de bola' WHERE id = 99;
UPDATE trees SET nome_popular = 'Ipê branco' WHERE id = 104;
UPDATE trees SET nome_popular = 'Pau-rei' WHERE id = 106;
UPDATE trees SET nome_popular = 'Açoita-cavalo' WHERE id = 108;
UPDATE trees SET nome_popular = 'Cabreúva-amarela' WHERE id = 110;
UPDATE trees SET nome_popular = 'Cabreúva-vermelha' WHERE id = 111;
UPDATE trees SET nome_popular = 'Cambuí' WHERE id = 115;
UPDATE trees SET nome_popular = 'Canafístula' WHERE id = 116;
UPDATE trees SET nome_popular = 'Capororoca' WHERE id = 117;
UPDATE trees SET nome_popular = 'Caputuna-preta' WHERE id = 118;
UPDATE trees SET nome_popular = 'Caqui-do-mato, olho-de-boi' WHERE id = 119;
UPDATE trees SET nome_popular = 'Catiguá' WHERE id = 122;
UPDATE trees SET nome_popular = 'Catiguá vermelho' WHERE id = 123;
UPDATE trees SET nome_popular = 'Cerejeira-do-rio-grande' WHERE id = 125;
UPDATE trees SET nome_popular = 'Copaíba' WHERE id = 127;
UPDATE trees SET nome_popular = 'Corrupita, abricó-de-macaco' WHERE id = 129;
UPDATE trees SET nome_popular = 'Craveiro-da-índia' WHERE id = 130;
UPDATE trees SET nome_popular = 'Dedaleira' WHERE id = 131;
UPDATE trees SET nome_popular = 'Embira-de-sapo, feijão cru' WHERE id = 132;
UPDATE trees SET nome_popular = 'Falsa murta' WHERE id = 133;
UPDATE trees SET nome_popular = 'Falso-timbó, ingá-bravo' WHERE id = 134;
UPDATE trees SET nome_popular = 'Folha-de-castanha' WHERE id = 136;
UPDATE trees SET nome_popular = 'Fruto-de-pombo, murta-branca' WHERE id = 137;
UPDATE trees SET nome_popular = 'Genipapo' WHERE id = 138;
UPDATE trees SET nome_popular = 'Guaçatonga' WHERE id = 140;
UPDATE trees SET nome_popular = 'Guaraiuva' WHERE id = 141;
UPDATE trees SET nome_popular = 'Guarantã' WHERE id = 142;
UPDATE trees SET nome_popular = 'Guaritá' WHERE id = 143;
UPDATE trees SET nome_popular = 'Ingá do brejo' WHERE id = 144;
UPDATE trees SET nome_popular = 'Ipê amarelo' WHERE id = 145;
UPDATE trees SET nome_popular = 'Ipê amarelo' WHERE id = 146;
UPDATE trees SET nome_popular = 'Ipê amarelo' WHERE id = 147;
UPDATE trees SET nome_popular = 'Ipê amarelo' WHERE id = 148;
UPDATE trees SET nome_popular = 'Ipê amarelo da mata' WHERE id = 149;
UPDATE trees SET nome_popular = 'Ipê amarelo do brejo' WHERE id = 150;
UPDATE trees SET nome_popular = 'Ipê rosa' WHERE id = 151;
UPDATE trees SET nome_popular = 'Ipê roxo anão' WHERE id = 152;
UPDATE trees SET nome_popular = 'Ipê roxo de bola' WHERE id = 153;
UPDATE trees SET nome_popular = 'Ipê-roxo' WHERE id = 154;
UPDATE trees SET nome_popular = 'Jacarandá paulista' WHERE id = 155;
UPDATE trees SET nome_popular = 'Jequitibá branco' WHERE id = 161;
UPDATE trees SET nome_popular = 'Jequitibá rosa' WHERE id = 162;
UPDATE trees SET nome_popular = 'Lofântera' WHERE id = 163;
UPDATE trees SET nome_popular = 'Louro pardo' WHERE id = 164;
UPDATE trees SET nome_popular = 'Magnólia' WHERE id = 165;
UPDATE trees SET nome_popular = 'Magnólia amarela' WHERE id = 166;
UPDATE trees SET nome_popular = 'Manacá-da-serra' WHERE id = 167;
UPDATE trees SET nome_popular = 'Maria-mole' WHERE id = 168;
UPDATE trees SET nome_popular = 'Marinheiro, camboatã' WHERE id = 169;
UPDATE trees SET nome_popular = 'Mulungu' WHERE id = 172;
UPDATE trees SET nome_popular = 'Nó-de-porco, resedá nacional' WHERE id = 174;
UPDATE trees SET nome_popular = 'Pata-de-vaca' WHERE id = 177;
UPDATE trees SET nome_popular = 'Pata-de-vaca' WHERE id = 178;
UPDATE trees SET nome_popular = 'Pata-de-vaca rosa' WHERE id = 179;
UPDATE trees SET nome_popular = 'Pata-de-vaca roxa' WHERE id = 180;
UPDATE trees SET nome_popular = 'Pau cigarra' WHERE id = 181;
UPDATE trees SET nome_popular = 'Pau d''alho' WHERE id = 182;
UPDATE trees SET nome_popular = 'Pau mulato' WHERE id = 183;
UPDATE trees SET nome_popular = 'Pau-ripa' WHERE id = 189;
UPDATE trees SET nome_popular = 'Peito-do-pombo' WHERE id = 190;
UPDATE trees SET nome_popular = 'Pindaiva' WHERE id = 193;
UPDATE trees SET nome_popular = 'Pinha-do-brejo' WHERE id = 194;
UPDATE trees SET nome_popular = 'Quaresmeira' WHERE id = 195;
UPDATE trees SET nome_popular = 'Quereltéria' WHERE id = 196;
UPDATE trees SET nome_popular = 'Pau-terra, jundiaí' WHERE id = 197;
UPDATE trees SET nome_popular = 'Resedá de folha graúda' WHERE id = 198;
